### ISSUE TITLE
Browser testing for new chrisproject.org site

### ISSUE THREAD

**Issue by mairin** [FNNDSC/website#20]
@Stan-Green-PM is interested in this issue.

The test site is https://mairin.github.io/chris-testing

**Comment by mairin** [comment]
This is the list of 10 heuristics mentioned on the call: https://www.nngroup.com/articles/ten-usability-heuristics/

**Comment by Stan-Green-PM** [comment]
I finally got the time to do some testing, but I get a 404 when I try to access: https://mairin.github.io/chris-testing

I may have time next week. Can @mairin get the site working again by then?

**Comment by junaruga** [comment]
Nice! Thank you @Stan-Green-PM .

**Comment by junaruga** [comment]
https://mairin.github.io/chris-testing is 404 not found now. What happened?

**Comment by mairin** [comment]
@junaruga it's pushed live to http://chrisproject.org!

**Comment by junaruga** [comment]
OK, why is this ticket still in the open status?

**Comment by mairin** [comment]
@junaruga because it still needs testing. I did some of my own light testing before pushing but I definitely still need @Stan-Green-PM 's help.

**Comment by junaruga** [comment]
Sure. Okay. Thanks for the explanation.

**Comment by Stan-Green-PM** [comment]
@mairin I found my first issue (broken link) with the site. What do you want me to do with it? I am new to GitHub so I don't want to mess it up. Thanks.

**Comment by mairin** [comment]
@Stan-Green-PM fabulous! You could just drop it here as a comment. I think that'll work for now.

**Comment by Stan-Green-PM** [comment]
@mairin Broken Link: On the home page, the link for the Creating Chris video point to: https://redhat.comvchris/ which should be: https://redhat.com/chris/

**Comment by Stan-Green-PM** [comment]
Accessibility:
The following images to do not have an ALT tag to provide a screen reader information about the image:
Image without ALT attribute	Found on page
https://chrisproject.org/assets/images/illus_collaborate.png	/about
https://chrisproject.org/assets/images/icons/role-docs.png	/join-us
https://chrisproject.org/assets/images/illus_data.png	/about
https://chrisproject.org/assets/images/demo_feed.jpg	/demo
https://chrisproject.org/assets/images/icons/role-marketing.png	/join-us
https://chrisproject.org/assets/images/icons/role-design.png	/join-us
https://chrisproject.org/assets/images/icons/role-backend.png	/join-us
https://chrisproject.org/assets/images/icons/tech-openstack.png	/join-us
https://chrisproject.org/assets/images/thumb_chris-store.jpg	/
https://chrisproject.org/assets/images/join.png	/join-us
https://chrisproject.org/assets/images/icons/tech-django.png	/join-us
https://chrisproject.org/assets/images/icons/tech-kube.png	/join-us
https://chrisproject.org/assets/images/icons/role-qa.png	/join-us
https://chrisproject.org/assets/images/demo_login.jpg	/demo
https://chrisproject.org/assets/images/thumb_creating-chris.jpg	/
https://chrisproject.org/assets/images/demo_output.jpg	/demo
https://chrisproject.org/assets/images/illus_compute.png	/about
https://chrisproject.org/assets/images/demo_feeds.jpg	/demo
https://chrisproject.org/assets/images/icons/tech-python.png	/join-us
https://chrisproject.org/assets/images/icons/role-frontend.png	/join-us
https://chrisproject.org/assets/images/icons/tech-react.png	/join-us
https://chrisproject.org/assets/images/icons/tech-js.png	/join-us

**Comment by Stan-Green-PM** [comment]
SEO:
The following are issues which will lower the SEO of the site.

Short page titles (Page titles longer than 30 characters are better for SEO.)
/credits
/join-us
/
/tags
/code

Short of no Page Description (the page description should be between 50-160 characters, Google will truncate descriptions longer than 160 characters):
/tags
/
/plugins
/join-us
/about
/credits
/code
/demo
/docs

**Comment by Stan-Green-PM** [comment]
Performance:
From an SEO point of view, the site does not perform well in regards to SEO performance. (i.e. Google "punishes" slow sites.)

A scan performed using the WebCEO tool showed the desktop is on the slow side (72%) but mobile is very slow (38%). 

The complete scan dashboard is attached. If more detail is needed on a given section of the report, the data is available for 10 days.
[Project Dashboard https_chrisproject_org 2020_12_02.pdf](https://github.com/FNNDSC/website/files/5638282/Project.Dashboard.https_chrisproject_org.2020_12_02.pdf)

**Comment by Stan-Green-PM** [comment]
HTTP/HTTPS:
If the main site is entered as ChrisProject.org is used, the HTTP site is used rather than HTTPS. (Google gives higher rankings to sites that use HTTPS.)

**Comment by Stan-Green-PM** [comment]
Broken Link: In the site footer, the link in the copyright statement is to: https://chrisproject.org/www.fnndsc.org. Also, the entire copyright statement is not linked; maybe there should be two links.

**Comment by Stan-Green-PM** [comment]
Home Page observations: 
1.	The image on the home page (http://chrisproject.org/assets/images/diagram_chris-arch.png) is hard to read for the vertical text on the left-hand side.
2.	On the homepage, in the “The ChRIS Store” box, the sentence “We link to a recent prototype here.” Is confusing. Is the here expected to be a link or is the link to the store a prototype? Is this sentence even needed?

**Comment by Stan-Green-PM** [comment]
Home Page Brower Differences (Using Chrome as the base.)
Browser: Internet Explorer 11.630.19041
1) Text overlaying the top video is not vertically centered. It is aligned to the top of the video.
2) Image for FNNDSC in footer does not display. May need to add “viewbox” (https://stackoverflow.com/questions/41831355/svg-not-rendering-ie-11)

Browser: Safari 13.1.2
The Youtube video preview is only filling half of the frame. The part being shown is the center of the video.

**Comment by Stan-Green-PM** [comment]
About Page:
The link to Boston University is coded as https://bu.edu/rhcollab/projects/radiology. However, the site’s SSL Cert is for www.bu.edu. The link should be changed to https://www.bu.edu/rhcollab/projects/radiology to avoid an SSL error.

In the overview paragraph, MOC is  listed as “the Massachusetts Open Cloud” but should be “Massachusetts Open Cloud”

In the “How does ChRIS work? “ section, FreeSurfer is linked to a search engine result, but why not link directly to https://surfer.nmr.mgh.harvard.edu/fswiki ? There is no guarantee a search engine will always return the same result set. If people want to know more, they can use their preferred search engine. The other two technologies are directly linked to their main site, so why is FreeSurfer different?

In the “How is ChRIS being used today?” section, “Boston Children’s Hospital (BCH)” is mislinked to “FNNDSC”

The “Boston Children's Hospital Team” is nice, but could be improved with a short statement from each person about the project.

**Comment by Stan-Green-PM** [comment]
Page: Demo
The instructions for Log In states, “The login screen will be pre-populated with a demo username and password that will enable you to log into the UI.” However, no pre-populated data is provided on the login page.

Page: Plugins – Could you a little more content and context here.

Join us:
Maybe “These are some of the skillsets we're looking for.” Could be reworked as: It takes many different skill sets to build ChRIS. If you have any of these skills, you could help develop ChRIS. If you have other skills you would like to contribute to ChRIS, please let us know.
For the skillsets icons, I would like to see some more description links.

For the “New Contributor Library” should the Under Construction items be removed until they are ready? (I am not a big fan of Under Construction.) If we are going to keep them, then the links should be removed as this give the appearance of a page, but the link only referenced back to the “Join Us” page. Also, if we are keeping them, the ready date should be updated as it is now in the past.

Page: Docs
There seems to be some overlap between “Join Us” and “Docs” (e.g. Get ChRIS Up and Running on Your Laptop). Should these items be consolidated or at least cross-linked?
Browser: IE 11
The website https://chrisstore.co/quickstart does not renter on IE. I only get a blank page. Although external sites are out of scope for these tests, since this is the ChRIS store, it has been included.

Page: Code
Since there is no content on this page, should there be a link for it?

**Comment by Stan-Green-PM** [comment]
@mairin @junaruga I have finished going through the site. Let me know if you have any questions. Thanks.

**Comment by mairin** [comment]
Awesome thanks @Stan-Green-PM ! I am going to create issues around each thing identified so we can tackle one by one and then close this ticket. Thank you so much for the work!
