### ISSUE TITLE
ALT tags needed for ChRIS website images

### ISSUE THREAD

**Issue by mairin** [FNNDSC/website#23]
Accessibility:
The following images to do not have an ALT tag to provide a screen reader information about the image:
Image without ALT attribute Found on page
https://chrisproject.org/assets/images/illus_collaborate.png	/about
https://chrisproject.org/assets/images/icons/role-docs.png	/join-us
https://chrisproject.org/assets/images/illus_data.png	/about
https://chrisproject.org/assets/images/demo_feed.jpg	/demo
https://chrisproject.org/assets/images/icons/role-marketing.png	/join-us
https://chrisproject.org/assets/images/icons/role-design.png	/join-us
https://chrisproject.org/assets/images/icons/role-backend.png	/join-us
https://chrisproject.org/assets/images/icons/tech-openstack.png	/join-us
https://chrisproject.org/assets/images/thumb_chris-store.jpg	/
https://chrisproject.org/assets/images/join.png	/join-us
https://chrisproject.org/assets/images/icons/tech-django.png	/join-us
https://chrisproject.org/assets/images/icons/tech-kube.png	/join-us
https://chrisproject.org/assets/images/icons/role-qa.png	/join-us
https://chrisproject.org/assets/images/demo_login.jpg	/demo
https://chrisproject.org/assets/images/thumb_creating-chris.jpg	/
https://chrisproject.org/assets/images/demo_output.jpg	/demo
https://chrisproject.org/assets/images/illus_compute.png	/about
https://chrisproject.org/assets/images/demo_feeds.jpg	/demo
https://chrisproject.org/assets/images/icons/tech-python.png	/join-us
https://chrisproject.org/assets/images/icons/role-frontend.png	/join-us
https://chrisproject.org/assets/images/icons/tech-react.png	/join-us
https://chrisproject.org/assets/images/icons/tech-js.png	/join-us

see https://github.com/FNNDSC/website/issues/20

**Comment by ChitvanRamani22** [comment]
@mairin could you please assign this to me

**Comment by ChitvanRamani22** [comment]
@mairin is this repository a part of outreachy 2021?

**Comment by archijaiswal** [comment]
Hi, could you please assign this issue to me?
I'm an Outreachy applicant, looking for good-first-issues to get comfortable with the project. @mairin @jennydaman
