### ISSUE TITLE
ChRIS website should use https by default

### ISSUE THREAD

**Issue by mairin** [FNNDSC/website#26]
HTTP/HTTPS:
If the main site is entered as ChrisProject.org is used, the HTTP site is used rather than HTTPS. (Google gives higher rankings to sites that use HTTPS.)

see https://github.com/FNNDSC/website/issues/20

**Comment by iranzo** [comment]
Can you just put in the DNS to do the upgrade? when using, for example cloudflare as DNS management it can allow, in the free tier, to do a rewrite rule to upgrade to https.

**Comment by kobi86** [comment]
Hi @mairin, 
Where the site is hosted? 
I mean, if its on IIS then just disable the HTTP if its on Nginx then you need some configuration changes :) 
We can have a session and talk about this if you want :)

**Comment by jfargen** [comment]
The site is hosted on github.io. This [doc](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https), show how https can be enforced, but any links referncing http://chrisproject.org will also need to be updated just prior/during to the change.

**Comment by iranzo** [comment]
If you're in control of the DNS, and don't mind moving it to CloudFlare, and have cloudflare point back to GH pages, you can get http and https working.

All links should be on the site rewritten to be protocol agnostic using the "//" in front instead of specifying the protocol so that both versions should work.

But, still, CF will do the https upgrade on http connections

**Comment by jfargen** [comment]
Pablo, my first recommendation is Cloudflare, but also trying to be flexible and provide solutions within the current architecture. I've also pointed out other benefits of Cloud Flare like the CDN with 200+ points of presence along with the site Analytics.

**Comment by mairin** [comment]
This work is complete, closing the ticket. Thanks to everyone who helped us out!
