### ISSUE TITLE
Confusions to address on chrisproject.org front page

### ISSUE THREAD

**Issue by mairin** [FNNDSC/website#28]
Home Page observations:

    The image on the home page (http://chrisproject.org/assets/images/diagram_chris-arch.png) is hard to read for the vertical text on the left-hand side.
    On the homepage, in the “The ChRIS Store” box, the sentence “We link to a recent prototype here.” Is confusing. Is the here expected to be a link or is the link to the store a prototype? Is this sentence even needed?

see https://github.com/FNNDSC/website/issues/20#issuecomment-738319108

**Comment by archijaiswal** [comment]
Hey @mairin, @jennydaman, can you please assign this issue to me?

**Comment by jennydaman** [comment]
I believe this issue is stale.
