### ISSUE TITLE
Implement new block for top of "for-devs" section of website

### ISSUE THREAD

**Issue by mairin** [FNNDSC/website#42]
There is a "revamp" branch of the website with upcoming changes.

We would like the following mockup to be implemented in HTML/CSS, to be used as a banner/block on the for-devs page:

![cookiecutter-diagram](https://user-images.githubusercontent.com/799683/114939807-f7db3080-9e0e-11eb-9271-7f86be464486.png)

**Comment by OlaoluwaM** [comment]
Hey @mairin is this open to outside contributors or no?

**Comment by mairin** [comment]
@OlaoluwaM absolutely, all yours!

**Comment by OlaoluwaM** [comment]
Hey @mairin , I have a few questions if you do not mind.

**Comment by OlaoluwaM** [comment]
For the text editor aspect of the mockup, is there a way to accomplish the syntax highlighting outside using classes and such?
Will the editor section be interactive, can users switch to the see the contents of, lets say, __init__.py or __main__.py?

**Comment by OlaoluwaM** [comment]
Also, where will this mockup go, do I create a for-devs.html in the __pages dir of the "revamp" branch and keep it there?

**Comment by rudolphpienaar** [comment]
> For the text editor aspect of the mockup, is there a way to accomplish the syntax highlighting outside using classes and such?
> Will the editor section be interactive, can users switch to the see the contents of, lets say, **init**.py or **main**.py?

Probably having an interactive "file browser/viewer" would be way overkill but would be totally awesome were it possible.

**Comment by rudolphpienaar** [comment]
Also @OlaoluwaM  just to reiterate, this is all  on the `revamp` branch. I actually have something of a deadline to get the revamp out in a week, so for here and now better to just get something that works than go too deep down the rabbit hole. Any help you might provide will be much much appreciated!

**Comment by OlaoluwaM** [comment]
Ok sure, makes sense, could you let me know the exact deadline so I can work with it too

**Comment by OlaoluwaM** [comment]
Also, does all the CSS for each page live in screen.css?
If so, is there a way I am meant to separate it?

I found that for the "join-us.html" there is a top-level div with an id of "join," and that is used to id the styles for the page, should I do the same?  Like "#for-devs", then style away, or is there another way?

**Comment by rudolphpienaar** [comment]
The deadline is Red Hat Summit that starts April 27. So ideally I'd like have the revamp live next Friday.

The CSS does live in screen.css and no, you don't need to separate it.

You are free to style etc whatever way seems best to you.

**Comment by OlaoluwaM** [comment]
Sounds good. For the text editor bit, I was thinking maybe we could just use an image since we are opting for speed over OMGness 🤔?

**Comment by rudolphpienaar** [comment]
Yes -- also if you have skills in just improving the look and feel a bit of the landing page that would be awesome. I'm not that skilled in the minutiae of nice layout in raw html/css :-)

**Comment by OlaoluwaM** [comment]
I will try my best 😅

**Comment by OlaoluwaM** [comment]
> Yes -- also if you have skills in just improving the look and feel a bit of the landing page that would be awesome. I'm not that skilled in the minutiae of nice layout in raw html/css :-)

By "landing page" do you mean https://chrisproject.org/ or the for-dev bit?

**Comment by mairin** [comment]
@OlaoluwaM Let me know if you need any help with the image. The SVG is here but I am happy to export it in chunks or whatnot as needed: https://github.com/FNNDSC/cube-design/raw/master/website/cookiecutter-diagram.svg

**Comment by OlaoluwaM** [comment]
Hello, do you know where I could find the font you used for the mockup, or am I free to pick a font

**Comment by OlaoluwaM** [comment]
Actually, scratch that, using another font could have unintended (ugly) side effects. I'll stick to the default unless you want to change the default font

**Comment by OlaoluwaM** [comment]
Update!

So I have completed the textual bits, all that remains are the images, specifically the settings-ish image, the white image besides the text, and the editor below as an image

![For-Developers-The-ChRIS-Project](https://user-images.githubusercontent.com/37044906/115314386-b4e4ca00-a13a-11eb-8362-18a05e4e663d.png)

**Comment by OlaoluwaM** [comment]
![For-Developers-The-ChRIS-Project (1)](https://user-images.githubusercontent.com/37044906/115318107-a7cbd900-a142-11eb-80f9-84c464a47d06.png)

**Comment by mairin** [comment]
Hi @OlaoluwaM ! The font is Overpass, but it should be embedded in the website. From your screenshots it looks like it isn't properly loading. I would consider that a bug, if you are interested in investigating that would be very helpful :)

**Comment by OlaoluwaM** [comment]
Sure! What do you think of the update. I changed the icon if you do not mind

**Comment by mairin** [comment]
@OlaoluwaM It looks like a solid start! I would stick with the artwork in the mockup / svg, just because we know where the sourcing is from / the licensing, and the style is meant to match what is on the site (the one you included looks nice but the lines are darker and thicker so they contrast with what is already being used in the graphic style on the website.) 

I would suggest as a next step that you block out the different areas:

- the white metadata block in the upper right, for example - the square you have there you could set up to have a white background for now and we can swap in the background image after. And the text on the block (I would use a mono font for it) should be filled in.
- the sidebar in the lower left - I would block that out too with a white bg and fill in the text
- the terminal in the lower right - block that out with the right background color
- the arrows for the sidebar and terminal can hopefully be layered on top with css? 

What do you think?

**Comment by OlaoluwaM** [comment]
Hmm, okay you want me to outline those elements with solid color right?

 But couldn't I get the SVGs and put them there instead?

**Comment by OlaoluwaM** [comment]
Also for the text at the top-right corner I think I can recreate the block with CSS but it would also be good to have a backup SVG, just in case 😅

**Comment by OlaoluwaM** [comment]
Update!

![For-Developers-The-ChRIS-Project (2)](https://user-images.githubusercontent.com/37044906/115797410-77ca4300-a399-11eb-9397-37b4b9680fdd.png)

I did the turquoise arrow with CSS, but I doubt that would scale well. I believe an SVG would be better. Is there anything I need to add?

**Comment by OlaoluwaM** [comment]
The reason I didn't add the second file arrow was that it would cause positioning problems as we try to align the image with it. It would be better to take the sidebar arrow along with the contents.

**Comment by OlaoluwaM** [comment]
Another Update!

I used Figma to recreate the shape on top of the editor and exported it as an SVG so now it looks better

![For-Developers-The-ChRIS-Project (3)](https://user-images.githubusercontent.com/37044906/115799382-03de6980-a39e-11eb-9530-3790c9738c38.png)

Let me know what you think!

**Comment by rudolphpienaar** [comment]
Hey Olaoluwa --

I'm trying to fire up the revamp changes, but get this

```

docker-compose up                                                                                                                                                                                                                                      Starting website_jekyll_1 ... done
Attaching to website_jekyll_1
jekyll_1  | Configuration file: /srv/jekyll/_config.yml
jekyll_1  |             Source: /srv/jekyll
jekyll_1  |        Destination: /srv/jekyll/_site
jekyll_1  |  Incremental build: disabled. Enable with --incremental
jekyll_1  |       Generating... 
jekyll_1  |        Jekyll Feed: Generating feed for posts
jekyll_1  | jekyll 3.9.0 | Error:  Permission denied @ rb_sysopen - /srv/jekyll/_site/404.html
website_jekyll_1 exited with code 1
```

Some scratching on the web seemed to indicate this has to do with `JEKYLL_UID` and `JEKYLL_GID` env variables.
https://stackoverflow.com/questions/57503011/unable-to-build-cloned-jekyll-site-jekyll-3-8-5-error-permission-denied-d

Do you have any insights?

**Comment by OlaoluwaM** [comment]
I'm not sure, try running with root privileges, that is ``sudo docker-compose up``. 

Also, I found that you need to have ``dockerd`` (``sudo dockerd``) running as well with root privileges. That worked for me

**Comment by OlaoluwaM** [comment]
Also, you can delete the ``for-devs.scss`` file because I used a vscode extension to transpile it to CSS, so you can just edit that, or keep it if you want but you would need the ``Live Sass Compile`` extension for any changes to reflect. If you decide to go down the extension route let me know so I can send the ``settings.json`` file for it

**Comment by rudolphpienaar** [comment]
FWIW it seems that the `docker-compose up` only works if your UID is 1000. I'm
assuming that is what yours is. I wasn't able to get it to work with mine, so
for now I'm just using an account that has that UID. It's a bit annoying but it
works.

**Comment by ramyaparimi** [comment]
Is this still an open issue? If so, can I work on this??
