### ISSUE TITLE
ChRIS website: Rework front page text

### ISSUE THREAD

**Issue by mairin** [FNNDSC/website#5]
_Lisa Knight from Team-19 is going to be working on this task._

## Core Task

The front page text on chrisproject.org needs to be reworked to tell a coherent narrative about ChRIS and what it is, and lead into other parts of the site a little more gracefully. :) Right now it's got bits and pieces copied from difference sources and doesn't flow too well.

If you have ideas for better illustrations, my intern @madelinepeck is working on some illustrations that are on the About page and would likely be able to develop or fix up any new graphics you think this page might need.

The code for this page is here:
https://github.com/FNNDSC/website/blob/master/index.html

### List of competitive websites

Here is a list of websites with similar types of platforms that you can look to, to see what kind of messaging / info similar platforms are putting out there on their sites. This list was compiled by Jennings Zhang:

https://www.notion.so/3f3e69007196418c8d8e11753bd7e929?v=68a11620902a4461922f459e819d1d3b

### Text copy in need of editing

Here's a plaintext copy of the current text for editing, please feel free to work it up as much as needed, drop sections, add sections, rearrange, etc.!:

ChRIS is a general-purpose, open source distributed data and computation platform.

[ View a Demo ] [ Visit Our GitHub -> ]

---

ChRIS reduces the barrier to cloud and distributed computing for researchers and developers. 

---

You can easily convert existing analytics or create new ones.

Once your analytics are containerized for ChRIS, you'll immediately have the benefits of distributed, containerized workflows.

ChRIS uses leading open source technologies to standardize cloud-based healthcare application development, taking care of the infrastructure so medical researchers can focus on their data.

---

ChRIS includes a beautiful front-end that enables researchers to create, share, and run analytic workflows in the cloud exclusively within a graphical user interface. 

---

ChRIS workflows can run anywhere — on your laptop, in your lab, on an HPC, or in the cloud.

---

Through our strong partnership with Red Hat and the Massachusetts Open Cloud (MOC), you can deploy workflows to the MOC — while still maintaining ownership of your own data. 

---

Why use ChRIS?

ChRIS allows researchers the ability to simply deploy their applications in a cloud infrastructure with access to more data, more compute, and more collaboration to drive medical innovation.

---

 As more and more of our lives become ever intimately impacted by computing, open source, open standards, and open platforms are fundamentally important. 

---

The ChRIS Store

The ChRIS Store is where you can find, download, or contribute your own medical imaging analytical software for deployment on the ChRIS platform. We link to a recent prototype here.

---

Creating ChRIS

This video series created by Red Hat tells the story of the ChRIS project, introduces some of the people behind it, and lays out the ChRIS vision of cloud technology improving medical care.

---

ChRIS on theCUBE

Watch this great overview of ChRIS as explained by Dr. Ellen Grant and Dr. Rudolph Pienaar of Boston Children's Hospital in an interview with theCUBE during the 2019 Red Hat Summit in Boston, Massachusetts.

---

### Questions / etc.

If you're stuck, have any questions, or need help with anything don't hesitate. If you put a @mairin in any comment here I will get an alert and be able to take a look. You also have my email and feel free to reach out any time.

**Comment by junaruga** [comment]
Are you measuring the page's numbers, such as page view number, unique user number, conversion rate between pages, A/B test?
How do we know the rework is actually good or bad for visitors?

**Comment by mairin** [comment]
@junaruga the website hasn't actually been finished yet (what is there is just copypasta) so I think it would be premature to put any metrics on it right now!

**Comment by rudolphpienaar** [comment]
Yes -- the site is def what I'd consider alpha. The rework (or just work) is needed since the site currently is more a quick throw together of "stuff" rather than a cohesively designed experience.

**Comment by junaruga** [comment]
OK. Thanks for the explanation.

**Comment by junaruga** [comment]
Is this ticket working in progress or can be closed according to https://github.com/FNNDSC/website/issues/20#issuecomment-737275357?

**Comment by mairin** [comment]
This work is complete and pushed live. Thanks so much @lknightrh !
